#!/usr/bin/env bash
set -euo pipefail
log(){ echo "[$(date +'%F %T')] $*"; }

############################
# 0) 可調參數（必要時改）
############################
COMFY_ROOT="${COMFY_ROOT:-/workspace/ComfyUI}"
VENV_MAIN="${VENV_MAIN:-/venv/main}"
INSIGHTFACE_TAG="${INSIGHTFACE_TAG:-v0.7}"       # antelopev2 來源 release 版
COMFYUI_GIT_REF="${COMFYUI_GIT_REF:-}"           # 鎖定 ComfyUI 版本 (例: v0.3.57)，空字串=跟最新 master
DOWNLOAD_RETRY="${DOWNLOAD_RETRY:-3}"
HF_TOKEN="${HF_TOKEN:-}"                          # 如需 HuggingFace token 可在模板環境變數設定

# 模型 URL（依你的清單）
URL_JUGGER="https://huggingface.co/AiWise/Juggernaut-XL-V9-GE-RDPhoto2-Lightning_4S/resolve/main/juggernautXL_v9Rdphoto2Lightning.safetensors"
URL_IPADAPTER="https://huggingface.co/InstantX/InstantID/resolve/main/ip-adapter.bin"
URL_INSTANT_CN="https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/diffusion_pytorch_model.safetensors"
URL_TTPLANET="https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic/resolve/main/TTPLANET_Controlnet_Tile_realistic_v2_fp16.safetensors"
URL_NOMOS="https://huggingface.co/Phips/2xNomosUni_span_multijpg_ldl/resolve/main/2xNomosUni_span_multijpg_ldl.safetensors"

# 缺失節點（GitHub 倉庫）
GIT_MTB="https://github.com/melMass/comfy_mtb"                           # Note Plus (mtb)
GIT_MATH="https://github.com/evanspearman/ComfyMath"                     # CM_Number*
GIT_COMFYROLL="https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes"  # CR Upscale / CR Prompt
GIT_JW="https://github.com/jamesWalker55/comfyui-various"                # JWImageResizeByLongerSide / JWInteger

############################
# 1) 啟用 venv & 檢查 Python 3.11
############################
if [[ -f "${VENV_MAIN}/bin/activate" ]]; then
  # shellcheck disable=SC1090
  source "${VENV_MAIN}/bin/activate"
else
  log "!! 找不到虛擬環境 ${VENV_MAIN}，中止。"; exit 1
fi

PY_VER="$({ python - << 'PY'
import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")
PY
} 2>/dev/null || echo "unknown")"

if [[ "$PY_VER" != "3.11" ]]; then
  log "!! 檢測到 Python=$PY_VER ≠ 3.11。依需求禁止在 3.12/3.13 上安裝，已中止。"
  exit 2
fi
log "Python 版本 OK: $PY_VER"

apt-get update -y -qq || true
apt-get install -y -qq git unzip curl wget ca-certificates libgl1 libglib2.0-0 || true
python -m pip install --upgrade pip wheel setuptools || true

############################
# 2) 停 ComfyUI（避免更新時佔用）
############################
log "Stopping ComfyUI (if running)..."
supervisorctl stop comfyui >/dev/null 2>&1 || true

############################
# 3) 更新或鎖定 ComfyUI 版本
############################
if [[ -f "${COMFY_ROOT}/main.py" ]]; then
  log "Updating ComfyUI at ${COMFY_ROOT} ..."
  git -C "${COMFY_ROOT}" fetch --tags --depth=1 origin || true
  if [[ -n "${COMFYUI_GIT_REF}" ]]; then
    git -C "${COMFY_ROOT}" checkout -f "${COMFYUI_GIT_REF}"
  else
    git -C "${COMFY_ROOT}" reset --hard origin/master
  fi
  log "Installing ComfyUI requirements..."
  pip install --no-cache-dir -r "${COMFY_ROOT}/requirements.txt" || true
else
  log "!! 找不到 ComfyUI (${COMFY_ROOT})，略過更新。"
fi

############################
# 4) ComfyUI-Manager 安裝/更新 + security_level=weak
############################
MANAGER_DIR="${COMFY_ROOT}/custom_nodes/ComfyUI-Manager"
if [[ ! -d "${MANAGER_DIR}" ]]; then
  log "Installing ComfyUI-Manager..."
  mkdir -p "${COMFY_ROOT}/custom_nodes"
  git clone --depth 1 https://github.com/Comfy-Org/ComfyUI-Manager "${MANAGER_DIR}" || true
  pip install --no-cache-dir -r "${MANAGER_DIR}/requirements.txt" || true
else
  log "Updating ComfyUI-Manager..."
  git -C "${MANAGER_DIR}" pull --ff-only || true
  pip install --no-cache-dir -r "${MANAGER_DIR}/requirements.txt" || true
fi

set_manager_security(){
  local cfg="$1"
  mkdir -p "$(dirname "$cfg")"
  if [[ -f "$cfg" ]]; then
    if grep -qi '^security_level' "$cfg"; then
      sed -i -E 's/^security_level\s*=.*/security_level = weak/i' "$cfg"
    else
      echo -e "\nsecurity_level = weak" >> "$cfg"
    fi
  else
    cat > "$cfg" <<EOF
# Auto-generated by onescript
security_level = weak
EOF
  fi
  log "Security level set to 'weak' at: $cfg"
}
set_manager_security "${MANAGER_DIR}/config.ini"
set_manager_security "${COMFY_ROOT}/user/default/ComfyUI-Manager/config.ini"

############################
# 5) 安裝缺失節點（GitHub）
############################
install_node(){
  local repo="$1" name="$2"
  local dest="${COMFY_ROOT}/custom_nodes/${name}"
  if [[ -d "$dest/.git" ]]; then
    log "Updating node ${name} ..."
    git -C "$dest" pull --ff-only || true
  else
    log "Installing node ${name} from ${repo} ..."
    rm -rf "$dest" && git clone --depth 1 "$repo" "$dest" || true
  fi
  if [[ -f "$dest/requirements.txt" ]]; then
    pip install --no-cache-dir -r "$dest/requirements.txt" || true
  fi
}

install_node "${GIT_MTB}" "comfy_mtb"                            # Note Plus (mtb)
install_node "${GIT_MATH}" "ComfyMath"                           # CM_NumberUnary/ToInt/IntToFloat/IntToNumber
install_node "${GIT_COMFYROLL}" "ComfyUI_Comfyroll_CustomNodes"  # CR Upscale Image / CR Prompt Text
install_node "${GIT_JW}" "comfyui-various"                       # JWImageResizeByLongerSide / JWInteger

# 系統/py 相依：mediapipe 釘 3.11 用的穩定版 + protobuf<5；臉嵌入常見依賴
pip install --no-cache-dir "mediapipe==0.10.14" "protobuf<5" \
  "opencv-python-headless" "insightface==0.7.3" "onnxruntime==1.17.1" || true

############################
# 6) 修復 InstantIDFaceAnalysis 的 antelopev2
############################
INSIGHT_BASE="${COMFY_ROOT}/models/insightface"
INSIGHT_MODELS="${INSIGHT_BASE}/models"
ANTE_DIR="${INSIGHT_MODELS}/antelopev2"
ZIP_PATH="${INSIGHT_BASE}/antelopev2.zip"
mkdir -p "${INSIGHT_MODELS}"

# 讓 insightface 套件也能直接找到這個 models 目錄
export INSIGHTFACE_HOME="${INSIGHT_BASE}"
mkdir -p "${HOME}/.insightface"
if [[ ! -e "${HOME}/.insightface/models" ]]; then
  ln -s "${INSIGHT_MODELS}" "${HOME}/.insightface/models" || true
fi

log "Fixing InstantID antelopev2 ..."
rm -rf "${ANTE_DIR}" "${ZIP_PATH}" 2>/dev/null || true
ANTE_URL="https://github.com/deepinsight/insightface/releases/download/${INSIGHTFACE_TAG}/antelopev2.zip"

for i in $(seq 1 "${DOWNLOAD_RETRY}"); do
  log "Downloading antelopev2.zip (try $i/${DOWNLOAD_RETRY}) ..."
  if curl -fL "${ANTE_URL}" -o "${ZIP_PATH}"; then
    break
  fi
  sleep 2
done

if [[ -s "${ZIP_PATH}" ]]; then
  unzip -o "${ZIP_PATH}" -d "${INSIGHT_MODELS}" >/dev/null
  rm -f "${ZIP_PATH}"
  [[ -d "${ANTE_DIR}" ]] && log "antelopev2 installed to ${ANTE_DIR}" || log "!! 解壓後未見 ${ANTE_DIR}"
else
  log "!! 下載 antelopev2.zip 失敗"
fi

############################
# 7) 下載模型到指定資料夾
############################
mkdir -p \
  "${COMFY_ROOT}/models/checkpoints" \
  "${COMFY_ROOT}/models/instantid" \
  "${COMFY_ROOT}/models/controlnet" \
  "${COMFY_ROOT}/models/upscale_models"

dl(){
  local url="$1" dest="$2"
  local tmp="${dest}.part"
  local auth=()
  [[ -n "$HF_TOKEN" ]] && auth=(-H "Authorization: Bearer $HF_TOKEN")
  for i in $(seq 1 "${DOWNLOAD_RETRY}"); do
    log "Downloading $(basename "$dest") (try $i/${DOWNLOAD_RETRY}) ..."
    if curl -fL --connect-timeout 20 --retry 3 --retry-delay 2 "${auth[@]}" "$url" -o "$tmp"; then
      mv -f "$tmp" "$dest"
      log "Saved to $dest"
      return 0
    fi
    sleep 2
  done
  log "!! Download failed: $url"
  return 1
}

# checkpoints
dl "$URL_JUGGER"   "${COMFY_ROOT}/models/checkpoints/juggernautXL_v9Rdphoto2Lightning.safetensors" || true

# instantid
dl "$URL_IPADAPTER" "${COMFY_ROOT}/models/instantid/ip-adapter.bin" || true

# controlnet
dl "$URL_INSTANT_CN" "${COMFY_ROOT}/models/controlnet/diffusion_pytorch_model.safetensors" || true
dl "$URL_TTPLANET"   "${COMFY_ROOT}/models/controlnet/TTPLANET_Controlnet_Tile_realistic_v2_fp16.safetensors" || true

# upscale_models（下載為 .safetensors；為相容舊工作流，同名建立 .pth symlink）
NOMOS_DST="${COMFY_ROOT}/models/upscale_models/2xNomosUni_span_multijpg_ldl.safetensors"
dl "$URL_NOMOS" "$NOMOS_DST" || true
if [[ -f "$NOMOS_DST" ]]; then
  ln -sf "2xNomosUni_span_multijpg_ldl.safetensors" "${COMFY_ROOT}/models/upscale_models/2xNomosUni_span_multijpg_ldl.pth" || true
fi

############################
# 8) 重新啟動 ComfyUI
############################
log "Starting ComfyUI..."
supervisorctl start comfyui >/dev/null 2>&1 || supervisorctl restart comfyui || true
log "All done. ComfyUI 應已啟動（外部 8188 → 內部 18188）。"
