name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    environment: yet # <-- 這裡已新增環境名稱

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
